<header class="sticky" role="banner">
        <nav class="top-bar" role="navigation">
            <ul class="title-area">
                <li class="name">
                    <?php if ($this->getIsHomePage()):?>
                    <h1 class="logo">
                        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo">
                            <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
                        </a>
                    </h1>
                    <?php else:?>
                    <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo">
                        <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
                    <?php endif?>
                </li>
                <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
            </ul>
            <section class="top-bar-section">
                <ul class="left">
                    <li class="has-dropdown"><a href="#">Categories</a>
                        <?php echo $this->getChildHtml('topMenu') ?>
                    </li>
                    <li class="divider"></li>
                    <li class="has-form"><?php echo $this->getChildHtml('topSearch') ?></li>
                    <li class="divider hide-for-large">
                </ul>
                <ul class="right">
                    <li class="has-dropdown">
                        <a href="#"><i class="foundicon-smiley"></i> Profile</a>
                        <ul class="dropdown">
                            <li><a href="<?php echo $this->getUrl('customer/account') ?>">My account</a></li>
                            <li>
                                <?php if($this->helper('customer')->isLoggedIn()):   ?>
                                <a href="<?php echo $this->getUrl('customer/account/logout') ?>"><?php echo $this->__('Log out') ?></a>
                                <?php else: ?>
                                <a href="<?php echo $this->getUrl('customer/account/login') ?>"><?php echo $this->__('Log in') ?></a>
                                <?php endif; ?>
                            </li>
                        </ul>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <?php
                        $count = $this->helper('checkout/cart')->getSummaryCount();  //get total items in cart
                        $total = $this->helper('checkout/cart')->getQuote()->getGrandTotal(); //get total price
                        ?>
                        <?php if($count == 0):?>
                        <a class="cartgo" href="<?php echo $this->getUrl('checkout/cart') ?>"><i class="foundicon-cart"></i> <?php echo $this->__(' 0 Items', $count) ?> <?php echo $this->helper('checkout')->formatPrice(Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal()); ?></a>
                        <?php endif; ?>
                        <?php if($count == 1):?>
                        <a class="cartgo" href="<?php echo $this->getUrl('checkout/cart') ?>"><i class="foundicon-cart"></i> <?php echo $this->__(' 1 Item', $count) ?> <?php echo $this->helper('checkout')->formatPrice(Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal()); ?></a>
                        <?php endif; ?>
                        <?php if($count >= 2):?>
                        <a class="cartgo" href="<?php echo $this->getUrl('checkout/cart') ?>"><i class="foundicon-cart"></i> <?php echo $this->__(' %s Items', $count) ?> <?php echo $this->helper('checkout')->formatPrice(Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal()); ?></a>
                        <?php endif; ?>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a class="cartgo" href="<?php echo $this->getUrl('checkout') ?>"><i class="foundicon-right-arrow"></i> Go to Checkout</a>
                    </li>
                </ul>
            </section>
        </nav>
</header>