<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php if($this->getCollection()->getSize()): ?>

    <div class="pager row">
        <p class="amount small-12 large-4 columns">
            <?php if($this->getLastPageNum()>1): ?>
                <?php echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
            <?php else: ?>
                <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
            <?php endif; ?>
        </p>

        <div class="limiter small-12 large-4 columns">
            <form class="custom" action="">
                <div class="row collapse">
                    <div class="small-4 columns">
                        <span class="prefix"><?php echo $this->__('Show') ?></span>
                    </div>
                    <div class="small-4 columns">
                        <select>onchange="setLocation(this.value)">
                        <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                            <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                                <?php echo $_limit ?>
                            </option>
                        <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="small-4 columns"><span class="postfix"><?php echo $this->__('per page') ?></span></div>
                </div>
            </form>
        </div>

        <?php echo $this->getPagerHtml() ?>

    </div>

    <?php if( $this->isExpanded() ): ?>
    <div class="sorter row">
        <?php if( $this->isEnabledViewSwitcher() ): ?>
        <dl class="sub-nav small-12 large-6 columns">
            <?php $_modes = $this->getModes(); ?>
            <?php if($_modes && count($_modes)>1): ?>
            <dt><?php echo $this->__('View as') ?>:</dt>
            <?php foreach ($this->getModes() as $_code=>$_label): ?>
                <?php if($this->isModeActive($_code)): ?>
                    <dd class="active"><a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></a></dd>
                <?php else: ?>
                    <dd><a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></a></dd>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php endif; ?>
        </dl>
        <?php endif; ?>

        <div class="sort-by small-12 large-6 columns">
            <form class="custom" action="">
                <div class="row collapse">
                    <div class="small-4 columns">
                        <span class="prefix">Sort By:</span>
                    </div>
                    <div class="small-8 columns">
                        <select onchange="setLocation(this.value)">
                               <option value="<?php echo $this->getOrderUrl('position', 'asc') ?>"<?php if($this->isOrderCurrent('position') && $this->getCurrentDirection() == 'asc'): ?> selected="selected"<?php endif; ?>>
                                   Position
                               </option>
                               <option value="<?php echo $this->getOrderUrl('price', 'asc') ?>"<?php if($this->isOrderCurrent('price') && $this->getCurrentDirection() == 'asc'): ?> selected="selected"<?php endif; ?>>
                                   Price Low to High
                               </option>
                               <option value="<?php echo $this->getOrderUrl('price', 'desc') ?>"<?php if($this->isOrderCurrent('price') && $this->getCurrentDirection() == 'desc'): ?> selected="selected"<?php endif; ?>>
                                   Price High to Low
                               </option>
                        </select>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <?php endif; ?>
<?php endif ?>
