<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>

<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="<?php echo $this->getLang() ?>"> <!--<![endif]-->
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body id="page" <?php echo $this->getBodyClass()?' class="off-canvas hide-extras'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
    <?php echo $this->getChildHtml('global_notices') ?>
        <div class="page">
        <?php echo $this->getChildHtml('header') ?>
                <?php echo $this->getChildHtml('breadcrumbs') ?>
                <div class="row">
                    <section role="main">
                        <?php echo $this->getChildHtml('global_messages') ?>
                        <?php echo $this->getChildHtml('content') ?>
                    </section>
                    <section id="sidebar" role="complementary">
                        <?php echo $this->getChildHtml('left') ?>
                    </section>
                </div>
        <?php echo $this->getChildHtml('footer') ?>
    <?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
        </div>
</body>
</html>
